# Generated by Django 5.0.2 on 2025-03-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Category1')),
                ('slug', models.SlugField(unique=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Category1',
                'verbose_name_plural': 'categor',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='', verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=20000)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('category1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor', to='store.category1')),
            ],
        ),
    ]
