# Generated by Django 5.0.2 on 2025-03-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category1',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
